[tool.poetry]
name = "nvim"
version = "0.1.0"
description = ""
authors = ["Sushrit_Lawliet <sushrit.pk21@gmail.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.12"
debugpy = "^1.8.13"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
