# Extra packages installed only on Linux/NixOS hosts (on top of shared-packages.nix):
# desktop environment, GUI apps, and Linux-only tooling that has no macOS equivalent
# via nix (GUI apps there mostly come from Homebrew instead).
{ pkgs, unstable ? pkgs }:
with pkgs; [
  android-studio
  android-tools
  appeditor
  arduino
  arduino-cli
  binaryen
  boatswain
  brave
  bruno
  catppuccin-cursors
  catppuccin-gtk
  docker
  docker-client
  dockerfile-language-server
  dotnet-aspnetcore
  dotnet-runtime
  dotnet-sdk
  emacs
  fira-code
  firefox
  fnm
  gcc
  github-desktop
  gnome-boxes
  gnome-tweaks
  gnomeExtensions.blur-my-shell
  gnomeExtensions.dash-to-panel
  gnomeExtensions.gsconnect
  gnomeExtensions.pano
  gnomeExtensions.paperwm
  gnomeExtensions.pop-shell
  gnomeExtensions.space-bar
  gnomeExtensions.user-themes
  gnomeExtensions.vitals
  go
  grafana
  gtk3
  hyprpaper
  jetbrains.idea
  jira-cli-go
  k6
  kitty
  kubectl
  libiconv
  libreoffice
  libtorch-bin
  libvlc
  magnetic-catppuccin-gtk
  mosquitto
  mpv
  nautilus
  nitrogen
  nixfmt
  nodejs_24
  nsis
  nushell
  nvitop
  nyxt
  obs-studio
  obs-studio-plugins.wlrobs
  openrgb-with-all-plugins
  openssl
  osm2pgsql
  pavucontrol
  pgadmin4-desktopmode
  picom
  pika-backup
  podman
  podman-desktop
  podman-tui
  poetry
  postgresql_16
  prometheus
  prometheus-node-exporter
  protobuf
  protoc-gen-go
  protoc-gen-grpc-web
  protoc-gen-rust
  python314
  python314Packages.gpustat
  python314Packages.jupytext
  python314Packages.pip
  python314Packages.pyspark
  rabbitmqadmin-ng
  ripdrag
  rofi
  rust-analyzer
  sushi
  terraform-docs
  texliveFull
  thunderbird
  tor-browser
  transmission_4
  transmission_4-gtk
  # tuir is intentionally disabled here: upstream test suite fails on Python 3.13
  # with "decode() argument 'encoding' must be str, not MockStdscr".
  ueberzugpp
  unixtools.net-tools
  upx
  uv
  vlc
  wails
  waybar
  wezterm
  wlogout
  wrk2
  xfce.xfce4-settings
  xorg.libxcb
  yarn
  ytfzf
  zoom-us

  # tracked on the unstable channel
  unstable.catnip
  unstable.google-chrome
  unstable.halloy
  unstable.localsend
  unstable.microsoft-edge
  unstable.neovim
  unstable.opencode
  unstable.vscode
  unstable.ollama-cuda
  unstable.llama-cpp-cuda
]
